mixmaxhq/eslint-config-mixmax

README.md
package.json

Projects that do not use our `browser` configs will not need this dependency, so we don't want to
require it via `peerDependencies`.

Make `eslint-plugin-react` an optional dependency

---

index.js

From [Chuy's review](https://github.com/mixmaxhq/app/pull/2441#pullrequestreview-74870631) realized we are not checking for single vs double quote in JSX properties.
From [code-styles](https://github.com/mixmaxhq/code-styles/blob/master/README.md#js) looks like we want this.
| Use single quotes in all JS code, unless you have a string that has a single quote in it, in which case you can use double quotes.
Here's what the changes look like in an [app PR](https://github.com/mixmaxhq/app/pull/2580)

jsx-quotes prefer-single

---

README.md
browser/index.js
flow/index.js
index.js
node/flow.js
node/next.js
package.json
yarn.lock

I updated the `eslint`  dependency to support correctly parsing flow annotated files, and also had to upgrade the minimum supported `babel-eslint`version due to an issue when parsing flow type definitions ([issue here](https://github.com/eslint/eslint/issues/9767#issuecomment-353840674)).
This will be a major version change since it requires 4.X, but shouldn't introduce problems based on [the migration guide](https://github.com/eslint/eslint/blob/master/docs/user-guide/migrating-to-4.0.0.md).

Add flow compatibility

---

node/index.js
node/next.js
package-lock.json
package.json

We should be on the latest `eslint` version and can default to node 8 parsing options for all node projects.
I tested this on some of our larger projects (app, compose, notifications) and it doesn't cause any problems other than rules which have been added in previous commits. This will be a major version upgrade anyway though since it removes 'node/next'

Upgrade eslint to ^5.6 and deprecate "next"

---

index.js

Tested by linking:
```
[~/ (ryan/test)]$ npm run lint
> test@0.0.1 lint /Users/rfreebern
> eslint . --ext '.js, .jsx'
/Users/rfreebern/test.js
164:5  error  Expected an object to be thrown  no-throw-literal
169:5  error  Expected an object to be thrown  no-throw-literal
174:5  error  Expected an object to be thrown  no-throw-literal
✖ 3 problems (3 errors, 0 warnings)
```
😅

Adds no-throw-literal rule

---

package-lock.json
package.json

For an overview of changes, view the [migration guide](eslint/eslint:docs/user-guide/migrating-to-6.0.0.md@master) in addition, 
there are upgrades to:
* babel-eslint
* Using babel 7 internally
* Stops monkey patching for pre-eslint 5 features
* removes support for node 4
* eslint-plugin-react
* no breaking changes
* eslint-plugin-flowtype
* mixed is a weak type by default
These changes _may_ introduce eslint errors, but should not introduce
unwanted eslint errors. As such, this will be a major version change,
albeit a safe one.

 Upgrade eslint and plugins for latest changes

---

node/disable-require-atomic.js

Looks like the `require-atomic-update` option is a bit overzealous. I ran into the same issue in the salesforce module.

Add disable require atomic option

---

index.js

To avoid pitfalls of implicit and mixed return values. Details: https://eslint.org/docs/rules/consistent-return

Add consistent-return rule

---

package-lock.json
package.json
prettier/index.js

As a shorthand for our prettier config in eslint files. This lets us do:
``` 
{ extends: ['mixmax/node','mixmax/prettier'] }
```
instead of 
```
{
"extends": ["mixmax/node", "prettier"],
"plugins": ["prettier"],
"rules": {
"prettier/prettier": "error"
}
}
```

Add mixmax/prettier and optional dependencies

---

.eslintignore
.eslintrc.json
.prettierrc
browser/index.js
browser/legacy.js
browser/spec.js
flow/index.js
index.js
node/ava.js
node/disable-require-atomic.js
node/index.js
node/jest.js
node/spec.js
node/withJest.js
package-lock.json
package.json
prettier/index.js

The `mixmax/node/withJest` file can be used in lieu of `mixmax/node` + `mixmax/node/jest` across multiple `.eslintrc.json` files - this also supports having tests co-located with source.
We also now include prettier in the node config - this might be a breaking change, thoughts?

add node/withJest, include prettier in default node

---

flow/strict.js

This needs to be opt-in to avoid breaking the heck out of modules like odm.

feat: add strict flow config

---

node/index.js

This can get a bit tedious to always override the sourceType when using es module syntax in the rest of the codebase.

feat: override babel config file sourceType

---

index.js

```js
const obj = {
method: () => {
return true;
},
// becomes
method() {
return true;
},
// Not transformed.
method: () => true,
method: () => this.get(),
};
```

feat: object-shorthand avoidExplicitReturnArrows

---

flow/index.js

This can cause problems with `flow-typed` distributed files.

feat: ignore flow-typed/npm in flow config

---

node/index.js

A little hesitant to do this since 10.x doesn't support every es2020 feature per https://node.green/#ES2020, but I think the unsupported features are unlikely to be used (and will fail fast anyway).

feat: bump node ecmaVersion to support 10.x features

---

index.js
package-lock.json
package.json

Not entirely sure what our preferred ordering is - this is just my attempt at putting together some ordering rules that are helpful.
I recommend the use of [ESLint-Formatter](https://github.com/TheSavior/ESLint-Formatter) for sublime users with [`eslint_d`](https://github.com/mantoni/eslint_d.js) (see https://github.com/roadhump/SublimeLinter-contrib-eslint_d/issues/18).

feat: warn for misordered imports

---

README.md

remove old changelog from readme
Since it's now in a separate file.
None.
None.

docs(readme): remove old changelog from readme

---

README.md
package.json

Jira: found upgrading in app https://github.com/mixmaxhq/app/pull/10375.
es2020 that we upgraded to in https://github.com/mixmaxhq/eslint-config-mixmax/pull/50 requires eslint 6.2.0 or greater (https://github.com/eslint/eslint/commit/fee6acbe13cecd4c028e681e185fc6a6d6ba9452)
Low. This is bumping a dependency that we already use in many of our other codebases.
npm install this module. It should install eslint>=6.2.0 as a peer dependency.

fix: invalid ecmascript bug

---

index.js

Fix pattern used to match internal Mixmax packages with subfolders. 
The previous pattern was making the imports with nested folders to be at the top of the file, on top of external packages.
Before
After
Low. This should be easily upgraded by eslint's automated script.

fix: Mixmax internal imports misordered 

---

browser/index.js
index.js
package-lock.json
package.json

Move the react-fragment config to the browser env, fixing errors caused in node envs introduced in #71 
Also moves the plugin back to the optionalDeps.
That it doesn't fix the issue or the rule is not being correctly applied in web apps.
I've linked it with Mixmax's app repository and it's still applying the eslint rule introduced by #71.
I have also tested in a backend-only repo and it now doesn't throw a dependency error.

fix: fix react fragment rule config

---

README.md
browser/index.js
package-lock.json
package.json

This PR adds the plugin [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks) to the browser config, using the default settings. 
This plugin enforces the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html).
You may have to take a closer look at the files that violate the rules because they can't be automatically fixed.

feat: add eslint-plugin-react-hooks

---

typescript/index.js

Sometimes, for the mocks to work it is important
to import dependencies in a specific order.
* Ignore order linting for imports

feat: ignore order of imports for test files

---

package-lock.json
typescript/index.js

We should allow underscore prefixed unused variables - the same way typescript does.
small. i found this while updating @mixmaxhq/zoom and seems like the appropriate way to handle it.
link, test, deploy.
- [n/a] I've increased test coverage

fix: allow some unused varables

---

README.md
browser/index.js
flow/index.js
package-lock.json
package.json

Use the supported and maintained `@babel/eslint-parser` instead.
From what I can see, there aren't major changes we need to worry about. Other dependency changes were because I couldn't run `npm i @babel/eslint-parser` without fixing their required dependencies.
small. worst case 
link in app, run linting. ensure it works.

fix: remove deprecated babel parser

---

package-lock.json
package.json

> **Note** - Since this is a public repository, make sure that we're not publishing private data in the code, commit comments, or this PR.
> **Note for reviewers** - Please add a 2nd reviewer if the PR affects more than 15 files or 100 lines (not counting
`package-lock.json`), if it incurs significant risk, or if it is going through a 2nd review+fix cycle.
Upgrade to Typescript 5.
None perceived.
Merge.

feat: upgrade to Typescript 5
